version: "3"
services:
 #database:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: wp 
      MYSQL_ROOT: root 
      MYSQL_PASSWORD: nopassword
    networks:
      - wp
  #web server
  wordpress:
    ports: 
      - "4000:80"
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    volumes: ["./html:/var/www/html"]
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
    networks: 
      - wp
networks:
  wp:
volumes:
  db_data:
