version: '3.1'
services:
db:
 container_name: postgres-db
 image: postgres:latest
 restart: always
 volumes:
  - ./myData:/data/db
 environment:
  - POSTGRES_DATABASE=MyDatabase
  - POSTGRES _USER=User
  - POSTGRES _PASS=secretpassword
 ports:
  - 5432:5432